# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bridge_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 866)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.server = QtWidgets.QGroupBox(self.centralwidget)
        self.server.setGeometry(QtCore.QRect(30, 80, 271, 251))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.server.setFont(font)
        self.server.setObjectName("server")
        self.server_begin = QtWidgets.QPushButton(self.server)
        self.server_begin.setGeometry(QtCore.QRect(10, 205, 84, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.server_begin.setFont(font)
        self.server_begin.setObjectName("server_begin")
        self.server_client_list = QtWidgets.QListView(self.server)
        self.server_client_list.setGeometry(QtCore.QRect(10, 145, 251, 51))
        self.server_client_list.setObjectName("server_client_list")
        self.server_stop = QtWidgets.QPushButton(self.server)
        self.server_stop.setGeometry(QtCore.QRect(100, 205, 84, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.server_stop.setFont(font)
        self.server_stop.setObjectName("server_stop")
        self.server_status = QtWidgets.QLabel(self.server)
        self.server_status.setGeometry(QtCore.QRect(190, 210, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.server_status.setFont(font)
        self.server_status.setFrameShape(QtWidgets.QFrame.Box)
        self.server_status.setAlignment(QtCore.Qt.AlignCenter)
        self.server_status.setObjectName("server_status")
        self.server_url = QtWidgets.QLabel(self.server)
        self.server_url.setGeometry(QtCore.QRect(20, 110, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.server_url.setFont(font)
        self.server_url.setFrameShape(QtWidgets.QFrame.Box)
        self.server_url.setText("")
        self.server_url.setObjectName("server_url")
        self.server_IP_select = QtWidgets.QComboBox(self.server)
        self.server_IP_select.setGeometry(QtCore.QRect(50, 40, 201, 31))
        self.server_IP_select.setObjectName("server_IP_select")
        self.label_11 = QtWidgets.QLabel(self.server)
        self.label_11.setGeometry(QtCore.QRect(20, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.server_port = QtWidgets.QLineEdit(self.server)
        self.server_port.setGeometry(QtCore.QRect(50, 80, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.server_port.setFont(font)
        self.server_port.setObjectName("server_port")
        self.label_12 = QtWidgets.QLabel(self.server)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.client = QtWidgets.QGroupBox(self.centralwidget)
        self.client.setGeometry(QtCore.QRect(30, 340, 271, 181))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.client.setFont(font)
        self.client.setObjectName("client")
        self.client_port = QtWidgets.QLineEdit(self.client)
        self.client_port.setGeometry(QtCore.QRect(50, 70, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_port.setFont(font)
        self.client_port.setObjectName("client_port")
        self.label_3 = QtWidgets.QLabel(self.client)
        self.label_3.setGeometry(QtCore.QRect(20, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.client)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.client_IP = QtWidgets.QLineEdit(self.client)
        self.client_IP.setGeometry(QtCore.QRect(50, 40, 201, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_IP.setFont(font)
        self.client_IP.setObjectName("client_IP")
        self.client_begin = QtWidgets.QPushButton(self.client)
        self.client_begin.setGeometry(QtCore.QRect(10, 135, 84, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_begin.setFont(font)
        self.client_begin.setObjectName("client_begin")
        self.client_stop = QtWidgets.QPushButton(self.client)
        self.client_stop.setGeometry(QtCore.QRect(100, 135, 84, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_stop.setFont(font)
        self.client_stop.setObjectName("client_stop")
        self.client_url = QtWidgets.QLabel(self.client)
        self.client_url.setGeometry(QtCore.QRect(20, 100, 231, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.client_url.setFont(font)
        self.client_url.setFrameShape(QtWidgets.QFrame.Box)
        self.client_url.setText("")
        self.client_url.setObjectName("client_url")
        self.client_status = QtWidgets.QLabel(self.client)
        self.client_status.setGeometry(QtCore.QRect(190, 140, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.client_status.setFont(font)
        self.client_status.setFrameShape(QtWidgets.QFrame.Box)
        self.client_status.setAlignment(QtCore.Qt.AlignCenter)
        self.client_status.setObjectName("client_status")
        self.current_send = QtWidgets.QListView(self.centralwidget)
        self.current_send.setGeometry(QtCore.QRect(780, 560, 191, 241))
        self.current_send.setObjectName("current_send")
        self.current_receive = QtWidgets.QListView(self.centralwidget)
        self.current_receive.setGeometry(QtCore.QRect(540, 560, 191, 241))
        self.current_receive.setObjectName("current_receive")
        self.topic_list = QtWidgets.QTableWidget(self.centralwidget)
        self.topic_list.setGeometry(QtCore.QRect(330, 110, 641, 411))
        self.topic_list.setObjectName("topic_list")
        self.topic_list.setColumnCount(2)
        self.topic_list.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.topic_list.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.topic_list.setHorizontalHeaderItem(1, item)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(330, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 530, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(540, 530, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(780, 530, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 60, 961, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(210, 15, 561, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.request_topic = QtWidgets.QTableWidget(self.centralwidget)
        self.request_topic.setGeometry(QtCore.QRect(30, 560, 461, 241))
        self.request_topic.setObjectName("request_topic")
        self.request_topic.setColumnCount(3)
        self.request_topic.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.request_topic.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_topic.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.request_topic.setHorizontalHeaderItem(2, item)
        self.topic_list.raise_()
        self.server.raise_()
        self.client.raise_()
        self.current_send.raise_()
        self.current_receive.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.line.raise_()
        self.label_10.raise_()
        self.request_topic.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.server_IP_select, self.server_port)
        MainWindow.setTabOrder(self.server_port, self.server_client_list)
        MainWindow.setTabOrder(self.server_client_list, self.server_begin)
        MainWindow.setTabOrder(self.server_begin, self.server_stop)
        MainWindow.setTabOrder(self.server_stop, self.client_IP)
        MainWindow.setTabOrder(self.client_IP, self.client_port)
        MainWindow.setTabOrder(self.client_port, self.client_begin)
        MainWindow.setTabOrder(self.client_begin, self.client_stop)
        MainWindow.setTabOrder(self.client_stop, self.topic_list)
        MainWindow.setTabOrder(self.topic_list, self.request_topic)
        MainWindow.setTabOrder(self.request_topic, self.current_receive)
        MainWindow.setTabOrder(self.current_receive, self.current_send)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.server.setTitle(_translate("MainWindow", "服务端"))
        self.server_begin.setText(_translate("MainWindow", "启动"))
        self.server_stop.setText(_translate("MainWindow", "停止"))
        self.server_status.setText(_translate("MainWindow", "未启动"))
        self.label_11.setText(_translate("MainWindow", "IP:"))
        self.server_port.setText(_translate("MainWindow", "9090"))
        self.label_12.setText(_translate("MainWindow", "port:"))
        self.client.setTitle(_translate("MainWindow", "客户端"))
        self.label_3.setText(_translate("MainWindow", "IP:"))
        self.label_4.setText(_translate("MainWindow", "port:"))
        self.client_begin.setText(_translate("MainWindow", "启动"))
        self.client_stop.setText(_translate("MainWindow", "停止"))
        self.client_status.setText(_translate("MainWindow", "未连接"))
        item = self.topic_list.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "结点名称"))
        item = self.topic_list.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "消息类型"))
        self.label.setText(_translate("MainWindow", "话题列表："))
        self.label_2.setText(_translate("MainWindow", "请求话题："))
        self.label_5.setText(_translate("MainWindow", "当前接收："))
        self.label_6.setText(_translate("MainWindow", "当前发送："))
        self.label_10.setText(_translate("MainWindow", "ROS话题通信控制终端"))
        item = self.request_topic.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "用户"))
        item = self.request_topic.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "请求"))
        item = self.request_topic.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "话题"))

